server:
  port: 9090
  servlet:
    context-path: /pilotInfo
  tomcat:
    max-http-form-post-size: -1   #请求大小 -1表示不限制
    max-http-header-size: 102400    #服务器的header缓冲区
spring:
  application:
    name: pilotInfo
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/pilot?useSSL=false&serverTimezone=UTC
    username: root
    password: YuZe0703
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5               #初始化时建立物理连接的个数
    min-idle: 5                   #最小连接池数量
    max-active: 20                #连接池中最多支持的活动会话
    max-wait: 60000               #获取连接的最大等待时间
    max-wait-millis: 200
    test-while-idle: true         #申请连接时检测,空闲时间大于timeBetweenEvictionRunsMillis,使用validationQuery检测连接是否有效
    validation-query: SELECT 1 FROM DUAL      #用来检测连接是否有效
    time-between-eviction-runs-millis: 60000  #连接空闲时间大于minEvictableIdleTimeMillis则关闭物理连接
    min-evictable-idle-time-millis: 300000    #连接保持空闲而不被驱逐的最小时间
    # true为开启，开启之后会降低性能
    test-on-borrow: false         #申请连接时执行validationQuery检测是否有效
    test-on-return: false         #归还连接时执行validationQuery检测是否有效
    pool-prepared-statements: true    #是否缓存preparedStatements
    # stat 监控统计,slf4j 日志,wall 防御sql注入
    filters: stat,wall,slf4j
    max-pool-prepared-statement-per-connection-size: 20
#    druid:
#      # 配置DruidStatFilter
#      web-stat-filter:
#        enabled: true
#        url-pattern: "/*"
#        exclusions: "/druid/*"
#      # 配置DruidStaViewServlet
#      stat-view-servlet:
#        enabled: true
#        url-pattern: "/druid/*"
#    schema:
#    - classpath:sql/pilot.sql


#设置为debug模式可以打印sql语句
logging:
  level:
    com: debug


mybatis-plus:
  type-aliases-package: com.pilot.boot.entity
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:mybatis/**/*.xml

  redis:
  #  url: redis://root:y12345678z@114.116.243.4:6379
    host: 127.0.0.1 #redis服务器地址
    port: 6379          #redis服务器连接端口
    password:          #redis服务器连接密码 默认为空
    timeout: 50000          #连接超时时间
    database: 0         #redis数据库索引
    ssl: enable
    pool:
      max-active: 8     #连接池最大连接数 使用负值表示没有限制
      max-wait: -1      #连接池最大阻塞等待时间 使用负值表示没有限制
      max-idle: 8       #连接池中的最大空闲连接
      min-idle: 0       #连接池中的最小空闲连接